// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFlWQG7Wa-i-UENrxiF_69i_36XAIwIy8',
    appId: '1:425551409628:web:0ca54cb6b49804916c1f19',
    messagingSenderId: '425551409628',
    projectId: 'immediate-graham',
    authDomain: 'immediate-graham.firebaseapp.com',
    storageBucket: 'immediate-graham.appspot.com',
    measurementId: 'G-KZT9SLH8WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhr4TWIV6uQ7kdBo8S8ixACsT7_dVXRVk',
    appId: '1:425551409628:android:8014ba50347a9ee26c1f19',
    messagingSenderId: '425551409628',
    projectId: 'immediate-graham',
    storageBucket: 'immediate-graham.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-2M7b6Pr588YJ1avFT1MDj6gRmGygRhM',
    appId: '1:425551409628:ios:d74042c41b2c18f76c1f19',
    messagingSenderId: '425551409628',
    projectId: 'immediate-graham',
    storageBucket: 'immediate-graham.appspot.com',
    iosClientId: '425551409628-8ee25aub2t3d3fark57h6lqgr0chj1r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-2M7b6Pr588YJ1avFT1MDj6gRmGygRhM',
    appId: '1:425551409628:ios:d74042c41b2c18f76c1f19',
    messagingSenderId: '425551409628',
    projectId: 'immediate-graham',
    storageBucket: 'immediate-graham.appspot.com',
    iosClientId: '425551409628-8ee25aub2t3d3fark57h6lqgr0chj1r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodLearning',
  );
}
